services:
  web:
    build: .
    image: server
    entrypoint: ./start.sh
    env_file:
      - .env
    ports:
      - "${SERVER_PORT:-8000}:8000"
  worker:
    image: server
    entrypoint: sh -c "python manage.py qcluster"
    depends_on:
      - web
    env_file:
      - .env
