# Generated by Django 6.0.2 on 2026-03-29 15:54

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.CharField(
                        choices=[
                            ("DESKTOP", "Desktop"),
                            ("MOBILE", "Mobile"),
                            ("TABLET", "Tablet"),
                            ("BOT", "Bot"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        choices=[
                            ("CHROME", "Chrome"),
                            ("SAFARI", "Safari"),
                            ("EDGE", "Edge"),
                            ("FIREFOX", "Firefox"),
                            ("OTHER", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "continent",
                    models.CharField(
                        choices=[
                            ("ASIA", "Asia"),
                            ("AFRICA", "Africa"),
                            ("NORTH_AMERICA", "North America"),
                            ("SOUTH_AMERICA", "South America"),
                            ("ANTARCTICA", "Antarctica"),
                            ("EUROPE", "Europe"),
                            ("OCEANIA", "Oceania"),
                        ],
                        max_length=13,
                        null=True,
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(max_length=2, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
