# Generated by Django 6.0.2 on 2026-04-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionparameters",
            name="access_token",
            field=models.CharField(editable=False, max_length=510, null=True),
        ),
    ]
