# Generated by Django 6.0.2 on 2026-04-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_sessionparameters_access_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionparameters",
            name="access_token",
        ),
        migrations.AlterField(
            model_name="sessionparameters",
            name="started_at",
            field=models.DateTimeField(),
        ),
    ]
