# Generated by Django 6.0.2 on 2026-04-27 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_remove_sessionparameters_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionparameters",
            name="access_token",
            field=models.CharField(max_length=511, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        choices=[
                            ("FIRST_VISIT", "First visit"),
                            ("BEGIN_CHECKOUT", "Begin checkout"),
                            ("PAGE_VIEW", "Page view"),
                            ("VIEW_ITEM", "View item"),
                            ("VIEW_SEARCH_RESULTS", "View search results"),
                            ("ADD_TO_CART", "Add to cart"),
                            ("VIEW_ITEM_LIST", "View item list"),
                            ("SELECT_ITEM", "Select item"),
                            ("PURCHASE", "Purchase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_data", models.CharField(blank=True, max_length=511, null=True)),
                ("timestamp", models.DateTimeField()),
                (
                    "session_parameters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.sessionparameters",
                    ),
                ),
            ],
        ),
    ]
