# Generated by Django 6.0.2 on 2026-04-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_sessionparameters_access_token_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sessionparameters",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
