colors = {
    "RED": {
        "RED", "DARKRED", "FIREBRICK", "CRIMSON", "INDIANRED",
        "LIGHTCORAL", "SALMON", "DARKSALMON", "LIGHTSALMON",
    },
    "PINK": {
        "PINK", "LIGHTPINK", "HOTPINK", "DEEPPINK",
        "PALEVIOLETRED", "MEDIUMVIOLETRED",
    },
    "ORANGE": {
        "ORANGE", "DARKORANGE", "CORAL", "TOMATO", "ORANGERED",
    },
    "YELLOW": {
        "YELLOW", "LIGHTYELLOW", "LEMONCHIFFON", "LIGHTGOLDENRODYELLOW",
        "PAPAYAWHIP", "MOCCASIN", "PEACHPUFF", "PALEGOLDENROD",
        "KHAKI", "DARKKHAKI", "GOLD", "GOLDENROD", "DARKGOLDENROD",
        "CORNSILK", "BLANCHEDALMOND",
    },
    "GREEN": {
        "GREEN", "LIME", "LIMEGREEN", "DARKGREEN", "FORESTGREEN",
        "SEAGREEN", "MEDIUMSEAGREEN", "SPRINGGREEN", "MEDIUMSPRINGGREEN",
        "LIGHTGREEN", "PALEGREEN", "DARKSEAGREEN", "YELLOWGREEN",
        "CHARTREUSE", "LAWNGREEN", "GREENYELLOW", "OLIVEDRAB",
        "DARKOLIVEGREEN", "OLIVE",
    },
    "CYAN": {
        "CYAN", "AQUA", "DARKCYAN", "LIGHTCYAN", "PALETURQUOISE",
        "AQUAMARINE", "MEDIUMAQUAMARINE", "TURQUOISE", "MEDIUMTURQUOISE",
        "DARKTURQUOISE", "TEAL",
    },
    "BLUE": {
        "BLUE", "DARKBLUE", "MEDIUMBLUE", "NAVY", "MIDNIGHTBLUE",
        "ROYALBLUE", "STEELBLUE", "DODGERBLUE", "DEEPSKYBLUE",
        "CORNFLOWERBLUE", "SKYBLUE", "LIGHTSKYBLUE", "LIGHTBLUE",
        "POWDERBLUE", "LIGHTSTEELBLUE", "CADETBLUE",
    },
    "PURPLE": {
        "PURPLE", "REBECCAPURPLE", "INDIGO", "BLUEVIOLET",
        "DARKVIOLET", "DARKORCHID", "MEDIUMORCHID", "ORCHID",
        "MEDIUMPURPLE", "DARKMAGENTA", "MAGENTA", "FUCHSIA",
        "VIOLET", "PLUM", "THISTLE", "LAVENDER", "DARKSLATEBLUE",
        "SLATEBLUE", "MEDIUMSLATEBLUE",
    },
    "WHITE": {
        "WHITE", "SNOW", "HONEYDEW", "MINTCREAM", "AZURE",
        "ALICEBLUE", "GHOSTWHITE", "SEASHELL", "BEIGE", "OLDLACE",
        "FLORALWHITE", "IVORY", "ANTIQUEWHITE", "LINEN",
        "LAVENDERBLUSH", "MISTYROSE", "WHITESMOKE",
    },
    "GRAY": {
        "GRAY", "GREY", "DARKGRAY", "DARKGREY", "DIMGRAY", "DIMGREY",
        "LIGHTGRAY", "LIGHTGREY", "SLATEGRAY", "SLATEGREY",
        "DARKSLATEGRAY", "DARKSLATEGREY", "LIGHTSLATEGRAY",
        "LIGHTSLATEGREY", "GAINSBORO", "SILVER",
    },
    "BROWN": {
        "BROWN", "MAROON", "SADDLEBROWN", "SIENNA", "CHOCOLATE",
        "PERU", "SANDYBROWN", "BURLYWOOD", "TAN", "ROSYBROWN",
        "WHEAT", "BISQUE", "NAVAJOWHITE",
    },
    "BLACK": {
        "BLACK",
    },
}