# Generated by Django 6.0.2 on 2026-02-18 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating_avg",
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="reviews",
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_reviews",
                to="market.product",
            ),
        ),
    ]
