# Generated by Django 6.0.2 on 2026-03-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="status",
        ),
    ]
