# Generated by Django 6.0.2 on 2026-04-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("LAPTOP", "Laptops"),
                    ("PC", "Desktop PC`s"),
                    ("NETWORK_DEVICE", "Networking devices"),
                    ("PRINTER_SCANNER", "Printers & Scanners"),
                    ("PC_PART", "PC parts"),
                    ("OTHER", "Other products"),
                ],
                max_length=20,
            ),
        ),
    ]
