# Generated by Django 6.0.2 on 2026-03-10 13:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_remove_product_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.AddField(
            model_name="product",
            name="colors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=7)
            ),
            preserve_default=False,
        ),
    ]
