# Generated by Django 6.0.2 on 2026-02-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_product_rating_avg_product_reviews_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating_avg",
            field=models.FloatField(),
        ),
    ]
