# Generated by Django 6.0.2 on 2026-03-10 15:01

import django.contrib.postgres.fields
import market.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_remove_product_color_product_colors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=market.models._uuid_photo_save
            ),
        ),
    ]
