# Generated by Django 6.0.2 on 2026-02-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_alter_product_options_product_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="characteristics",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
