# Generated by Django 6.0.2 on 2026-02-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0006_product_characteristics_product_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(max_length=7),
        ),
    ]
