# Generated by Django 6.0.2 on 2026-04-01 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "session_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("session_url", models.CharField(max_length=1024)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PAID", "Paid"),
                            ("CANCELED", "Canceled"),
                        ],
                        max_length=10,
                    ),
                ),
                ("money_to_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                ("receipt", models.URLField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="market.order",
                    ),
                ),
            ],
        ),
    ]
