# Generated by Django 6.0.2 on 2026-03-19 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "session_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("session_url", models.CharField(max_length=1024)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PAID", "Paid"),
                            ("CANCELED", "Canceled"),
                        ],
                        max_length=10,
                    ),
                ),
                ("money_to_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.order"
                    ),
                ),
            ],
        ),
    ]
