# Generated by Django 6.0.2 on 2026-03-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="_check",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
