# Generated by Django 6.0.2 on 2026-03-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment__check"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="_check",
            new_name="receipt",
        ),
    ]
